<main class="posts container-fluid">
    <h1 class="page-header"><?=t('posts')?></h1>

    <table class="table table-hover table-striped">
        <thead>
            <th><?=t('title')?></th>
            <th><?=t('author')?></th>
            <th><?=t('published_at')?></th>
            <th></th>
        </thead>
        <tbody>
        <?php foreach ($posts as $post) : ?>
            <tr>
                <td><a href="<?=baseUrl('/admin/posts/' . $post['id'])?>"><?=$post['title']?></a></td>
                <td><?=$post['user_name']?></td>
                <td><?=$post['published_at']?></td>
                <td></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
