<main class="posts container-fluid">
    <h1 class="page-header"><?=t('posts')?></h1>

    <table class="table table-hover table-striped">
        <thead>
            <th><?=t('title')?></th>
            <th><?=t('author')?></th>
            <th><?=t('is_published')?></th>
            <th><?=t('published_at')?></th>
            <th></th>
        </thead>
        <tbody>
        <?php foreach ($posts as $post) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/posts/{$post['id']}/edit")?>"><?=$post['title']?></a></td>
                <td><?=$post['user_name']?></td>
                <td><span class="fa fa-<?=$post['is_published'] ? 'check' : 'times'?>"></span></td>
                <td><?=$post['published_at']?></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/posts/{$post['id']}/delete")?>" class="btn btn-xs btn-danger">
                            <span class="fa fa-trash"></span> <span class="sr-only"><?=t('delete')?></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
