<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Dreamer</title>
	</head>
	<body>
		<div class="container">
			<div id="wrapper">
				<nav class="navbar navbar-default">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
							<span class="sr-only"><?=t('toggle_navigation')?></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a href="<?=Request::baseUrl()?>" class="navbar-brand"><?=setting('title')?></a>
					</div>

					<div class="collapse navbar-collapse" id="navbar-collapse-1">
						<ul class="nav navbar-nav">

						</ul>
					</div>
				</nav>
				<main>
					<?=$this->getSection('content')?>
				</main>
				<footer id="footer">
					<div class="pull-right">
						Powered by <a href="https://nirix.github.io/dreamer">Dreamer</a>
					</div>

					&copy; <?=date("Y")?>
				</footer>
			</div>
		</div>
		<script src="<?=Request::baseUrl('assets/dreamer.js')?>"></script>
	</body>
</html>
