<div class="row">
    <div class="col-md-6">
        <div class="form-group <?=iif($page->hasError('name'), 'has-error')?>">
            <label for="name" class="control-label"><?=t('name')?></label>
            <input type="text" name="name" id="name" class="form-control" value="<?=$page['name']?>">
            <?php if ($page->hasError('name')) : ?>
                <div class="help-block"><?=errorMessageFor($page, 'name')?></div>
            <?php endif ?>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group <?=iif($page->hasError('slug'), 'has-error')?>">
            <label for="slug" class="control-label"><?=t('slug')?></label>
            <input type="text" name="slug" id="slug" class="form-control" data-type="slug" data-slug-from="#name" value="<?=$page['slug']?>">
            <?php if ($page->hasError('slug')) : ?>
                <div class="help-block"><?=errorMessageFor($page, 'slug')?></div>
            <?php endif ?>
        </div>
    </div>
</div>

<div class="form-group">
    <label for="content" class="control-label"><?=t('content')?></label>
    <textarea name="content" id="content" class="form-control"><?=$page['content']?></textarea>
</div>
