<main class="pages container-fluid">
    <h1 class="page-header"><?=t('pages')?></h1>

    <table class="table table-hover table-striped">
        <thead>
            <th><?=t('name')?></th>
            <th></th>
        </thead>
        <tbody>
        <?php foreach ($pages as $page) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/pages/{$page['id']}/edit")?>"><?=$page['name']?></a></td>
                <td>
                    <div class="text-right">
                        <a href="<?=baseUrl("/admin/pages/{$page['id']}/delete")?>" class="btn btn-xs btn-danger">
                            <span class="fa fa-trash"></span>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
