<main class="pages container-fluid">
    <h1 class="page-header"><?=t('pages')?></h1>

    <table class="table table-hover table-striped">
        <thead>
            <th><?=t('name')?></th>
            <th></th>
        </thead>
        <tbody>
        <?php foreach ($pages as $page) : ?>
            <tr>
                <td><a href="<?=baseUrl("/admin/pages/{$page['id']}/edit")?>"><?=$page['name']?></a></td>
                <td></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</main>
