<main class="new-page container-fluid">
    <h1 class="page-header"><?=t('new_page')?></h1>

    <form action="<?=baseUrl('/admin/pages/new')?>" method="post">
        <?=csrfField()?>

        <?=view('admin/pages/_form.phtml', ['page' => $page])?>

        <div class="form-group">
            <div class="text-center">
                <button type="submit" class="btn btn-primary"><?=t('create_page')?></button>
            </div>
        </div>
    </form>
</main>
