<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?=setting('title')?> / Login</title>
        <link rel="stylesheet" href="<?=baseUrl('/assets/css/admin.css')?>">
    </head>
    <body class="login">
        <div class="container">
            <form action="<?=baseUrl('/login')?>" method="post" class="form-login">
                <?=csrfField()?>

                <h2 class="form-login-heading">Please login</h2>

                <?php if ($error) : ?>
                <div class="alert alert-danger">
                    Invalid username and/or password.
                </div>
                <?php endif ?>

                <label for="username" class="sr-only">Username</label>
                <input type="text" name="username" id="username" class="form-control" placeholder="Username" required autofocus>

                <label for="password" class="sr-only">Password</label>
                <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>

                <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
            </form>
        </div>
    </body>
</html>
