<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?=implode(' / ', title())?></title>
        <link rel="stylesheet" href="<?=baseUrl('/assets/css/admin.css')?>">
    </head>
    <body class="login">
        <div class="container">
            <form action="<?=baseUrl('/login')?>" method="post" class="form-login">
                <?=csrfField()?>

                <h2 class="form-login-heading"><?=t('please_login')?></h2>

                <?php if ($error) : ?>
                <div class="alert alert-danger">
                    <?=t('errors.invalid_username_or_password')?>
                </div>
                <?php endif ?>

                <label for="username" class="sr-only"><?=t('username')?></label>
                <input type="text" name="username" id="username" class="form-control" placeholder="<?=t('username')?>" required autofocus>

                <label for="password" class="sr-only"><?=t('password')?></label>
                <input type="password" name="password" id="password" class="form-control" placeholder="<?=t('password')?>" required>

                <button class="btn btn-lg btn-primary btn-block" type="submit"><?=t('login')?></button>
            </form>
        </div>
    </body>
</html>
